# Generated by Django 4.2.6 on 2023-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hora_partida', models.TimeField()),
                ('costo_base', models.FloatField()),
            ],
            options={
                'db_table': 'itinerario',
                'managed': False,
            },
        ),
    ]
